apiVersion: v1
kind: Service
metadata:
  name: easy-shop-inventory-db-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: easy-shop-inventory-db
  ports:
    - port: 5432
      targetPort: 5432
