apiVersion: v1
kind: Service
metadata:
  name: easy-shop-db-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: easy-shop-db-service
  ports:
    - port: 5432
      targetPort: 5432
