apiVersion: v1
kind: Service
metadata:
  name: easy-shop-customer-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: easy-shop-customer-service
  ports:
    - port: 8085
      targetPort: 8085
