apiVersion: v1
kind: Service
metadata:
  name: easy-shop-customer-service-cluster-ip-server
spec:
  type: ClusterIP
  selector:
    component: easy-shop-customer-service
  ports:
    - port: 8081
      targetPort: 8081
