apiVersion: v1
kind: Service
metadata:
  name: easy-shop-auth-server-cluster-ip-server
spec:
  type: ClusterIP
  selector:
    component: easy-shop-auth-server
  ports:
    - port: 8081
      targetPort: 8081
