apiVersion: v1
kind: Service
metadata:
  name: easy-shop-tracing-server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: easy-shop-tracing-server
  ports:
    - port: 9411
      targetPort: 9411
