apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-shop-tracing-server-deployment
spec:
  replicas: 1
  # How to find the created pod
  selector:
    matchLabels:
      app: easy-shop-tracing-server
  template:
    metadata:
      # labels of created pod
      labels:
        # we can name whatever we want for labels
        app: easy-shop-tracing-server
    spec:
      containers:
        - name: easy-shop-tracing-server
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
