apiVersion: v1
kind: Service
metadata:
  name: easy-shop-zipkin-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: easy-shop-zipkin-service
  ports:
    - port: 9411
      targetPort: 9411
