apiVersion: v1
kind: Service
metadata:
  name: easy-shop-zookeeper-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: easy-shop-zookeeper
  ports:
    - port: 2181
      targetPort: 2181
