apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: easy-shop-order-db-stateful-set
spec:
  serviceName: easy-shop-order-db-stateful-set
  replicas: 1
  # How to find the created pod
  selector:
    matchLabels:
      app: easy-shop-order-db
  template:
    metadata:
      # labels of created pod
      labels:
        # we can name whatever we want for labels
        app: easy-shop-order-db
    spec:
      volumes:
        - name: easy-shop-order-db-storage
          persistentVolumeClaim:
            claimName: easy-shop-order-db-persistent-volum-claim
      containers:
        - name: easy-shop-order-db
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
              - name: easy-shop-order-db-storage
                mountPath: /var/lib/postgresql/data   # container path defined by postgres:alpine image
                # subPath: db
          env:
            # Pull environment variables from ConfigMap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: easy-shop-order-db-config-map
                  key: db-name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: easy-shop-order-db-config-map
                  key: db-user
            # Pull password from Secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: easy-shop-db-passwords
                  key: order-db
