apiVersion: v1
kind: Service
metadata:
  name: easy-shop-order-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: easy-shop-order-service
  ports:
    - port: 8086
      targetPort: 8086
